name: CI/CD Pipeline for Multiple Microservices

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Push Patient Service
        run: |
          docker build -t thellmike/patient-service:latest ./patient_service
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push thellmike/patient-service:latest

      - name: Build and Push Appointment Service
        run: |
          docker build -t thellmike/appointment-service:latest ./appointment_service
          docker push thellmike/appointment-service:latest

      - name: Build and Push Notification Service
        run: |
          docker build -t thellmike/notification-service:latest ./notification_service
          docker push thellmike/notification-service:latest

      - name: Install Argo CD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Login to Argo CD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }}

      - name: Trigger Argo CD Sync
        run: |
          argocd app sync patient-service
          argocd app sync appointment-service
          argocd app sync notification-service
